# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_users', '0002_auto_20170610_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='bankuser',
            name='creator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_user', to='bank_users.CustomUser'),
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
