# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_users', '0003_auto_20170611_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
