# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_users', '0004_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_create_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
