# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_users', '0005_auto_20170611_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
